#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "${HOME}/.cache/wal/colors.sh"


set_sublime() {
    ${HOME}/.config/sublime-text-3/Packages/wal/base16-wal.tmTheme.sh > ${HOME}/.config/sublime-text-3/Packages/wal/base16-wal.tmTheme
}

main() {
    set_sublime &
}

main >/dev/null 2>&1
